name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.13.0
        - name: Install
          run: npm install
        - name: Test
          env:
            BROWSERSTACK_USER: ${{ secrets.BS_USER }}
            BROWSERSTACK_KEY: ${{ secrets.BS_KEY }}
            BROWSERSTACK_ANDROID_APP: ${{ secrets.BS_ANDROID_APP }}
            BROWSERSTACK_IOS_APP: ${{ secrets.BS_IOS_APP }}
          run: npx wdio config/browserstack/wdio.android.bs.conf.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
